### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by VoroninIgor** [TomTork/JoJack-mobile-redsunshine#1]
Хотелось бы создать ReamMe файл для репозитория, чтобы было понятно, зачем он есть и как можно поучаствовать.
Допустим, пофиксить баг, порефакторить или предложить добавить свою фичк

Сегодня постараюсь сделать шаблон и завести на него ветку, так как ранее в контрибьюция на гитхабе не игрался)

Вот примеры, как это может выглядеть:

https://github.com/devopshq/ExampleProject/blob/master/README.md
https://gist.github.com/bzvyagintsev/0c4adf4403d4261808d75f9576c814c2

**Comment by TomTork** [comment]
В целом, согласен, README нужен. Тогда буду ждать шаблон)

**Comment by TomTork** [comment]
стоп, я закрыл. Теперь вроде снова открыл

**Comment by TomTork** [comment]
Сделал readme сам
